inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  DisplayStyleGuide: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

ParameterLists:
  Max: 10

Security/MarshalLoad:
  Enabled: false
