#AllCops:
#  TargetRubyVersion: 2.3

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['(\A|\s)#']

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

ParameterLists:
  Max: 10

Security/MarshalLoad:
  Enabled: false
