require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'ext/rumale/extconf.rb'
    - 'tmp/**/*.rb'
    - 'rumale.gemspec'
    - 'Rakefile'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 145
  AllowedPatterns: ['(\A|\s)#']

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 16

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 15

Security/MarshalLoad:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 25

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 40

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

Performance/Sum:
  Enabled: false
