require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'ext/rumale/extconf.rb'
    - 'rumale.gemspec'
    - 'Rakefile'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/LineLength:
  Max: 145
  IgnoredPatterns: ['(\A|\s)#']

Metrics/ModuleLength:
  Max: 200

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 60

Metrics/CyclomaticComplexity:
  Max: 16

Metrics/PerceivedComplexity:
  Max: 16

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'

Metrics/ParameterLists:
  Max: 15

Security/MarshalLoad:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Layout/EmptyLineAfterGuardClause:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/StringInclude:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 40

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false
