sudo: false
os: linux
dist: trusty
language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3

